language: cpp
sudo: false

compiler:
- clang
- gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

notifications:
  email: false
  
branches:
 only:
 - master
 - develop

