language: cpp
sudo: false
script: make
matrix:
  include:
    # works on debian-jessir
    - os: linux
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake
