sudo: false
language: cpp
matrix:
  include:
    # works on debian-stretch
    - os: linux
        services: docker
        env:
          - V=Dockerfile-note
        script:
          - ./archive.sh
          - docker build -f docker/dockernote/Dockerfile-note .
