language: cpp
sudo: false
dist: trusty
install: automake autoconf
script: make
matrix:
  include:
    # works on debian-jessir
    - os: linux
        services: docker
        env:
          - V=Dockerfile-note
        script:
          - ./archive.sh
          - docker build -f docker/dockernote/Dockerfile-note .
